package routes

import ()

var ActionsRoute = "/actions"
var ChamadosRoute = "/chamados"
var CiclosRoute = "/ciclos"
var ComponentesRoute = "/componentes"
var ElementosRoute = "/elementos"
var EntidadesRoute = "/entidades"
var EscritoriosRoute = "/escritorios"
var FeaturesRoute = "/features"
var PilaresRoute = "/pilares"
var PlanosRoute = "/planos"
var ProcessosRoute = "/processos"
var AnotacoesRoute = "/anotacoes"
var RadaresRoute = "/radares"
var RolesRoute = "/perfis"
var VersoesRoute = "/versoes"
var StatusRoute = "/status"
var TiposNotasRoute = "/tiposnotas"
var UsersRoute = "/users"
var WorkflowsRoute = "/workflows"
var AdminHome = "/admin"
var ChefeHome = "/chefe"
var SupervisorHome = "/supervisor"
var AuditorHome = "/auditor"
var VisualizadorHome = "/visualizador"
var DesenvolvedorHome = "/desenvolvedor"
