UPDATE VIRTUS.PRODUTOS_COMPONENTES SET ID_STATUS = NULL;
DELETE FROM VIRTUS.activities_roles
DELETE FROM VIRTUS.features_activities
DELETE FROM VIRTUS.activities
DELETE FROM VIRTUS.workflows
DELETE FROM VIRTUS.actions_status
DELETE FROM VIRTUS.actions
DELETE FROM VIRTUS.status WHERE id_status <> 0